Guadalajara/August2022/SmartSecurity/apps/IArosa/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
app_name = 'IArosa'

urlpatterns = [
    path(
        '', 
        views.LandingPageView.as_view(),
        name='index'
    ),
    path(
        'map/<month>/<year>', 
        views.Map1View.as_view(),
        name='map'
    ),
]

Guadalajara/August2022/SmartSecurity/socialis/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include("apps.IArosa.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.IArosa.views.error_404_view'

Guadalajara/August2022/SmartSecurity/apps/IArosa/models.py
from django.db import models

# Create your models here.

Guadalajara/August2022/SmartSecurity/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager

# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        max_length=40
    )
    email = models.EmailField(
        max_length=254, 
        unique=True
    )
    is_staff = models.BooleanField(
        default=False
    )
    is_superuser = models.BooleanField(
        default=False
    )
    is_active = models.BooleanField(
        default=False
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        abstract = False

    def __str__(self):
        return self.username

Guadalajara/August2022/SmartSecurity/apps/user/forms.py
from django import forms
from django.contrib.auth import authenticate
from datetime import date
from django.core.exceptions import ValidationError

from apps import user
from .models import User


my_default_errors = {
    'required': 'Este campo es requerido.',
    'invalid': 'Valor invalido.',
    'unique': 'Ya existe un usuario registrado con este correo.',
}


class UserRegisterForm(forms.ModelForm):

    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña'
            }
        )
    )

    email = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Correo'
            }
        ),
        error_messages=my_default_errors 
    )

    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Tu nombre(s)'
            }
        ) 
    )

    class Meta:
        model = User
        fields = (
            'username',
            'email',
        )

Guadalajara/August2022/SmartSecurity/apps/IArosa/views.py
from django.shortcuts import render
from django.views.generic import View, CreateView, ListView, TemplateView, UpdateView

from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from unipath import Path
import random

# Create your views here.
class LandingPageView(ListView):
    # la nueva direccion de los template es Album/----.html
    template_name = 'landingPage.html'
    context_object_name = 'fx'
    def get_queryset(self):
        return random.randint(1, 20), random.randint(1, 20)

class Map1View(ListView):
    template_name = 'IAmap.html'
    context_object_name = 'maps'

    def get_queryset(self):
        dataAI = [
            ['2022', 'Septiembre', '1,0,1,0,0,1,0,0,0,1,0,0,1,0,1,1'],
            ['2022', 'Octubre', '0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,1'],
            ['2022', 'Noviembre', '0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,1'],
        ]
        pkMonth = self.kwargs['month']
        pkYear = self.kwargs['year']
        month = ['Septiembre', 'Octubre', 'Noviembre']
        years = ['2022']
        # peticion o logica
        for x in dataAI:
            if x[0] == pkYear and x[1] == pkMonth:
                query = x[2].split(",")
        return query, month, years

def error_404_view(request, exception):
    return render(request, 'index/page404.html')

Guadalajara/August2022/SmartSecurity/apps/user/views.py
from django.shortcuts import render

# Create your views here.

Guadalajara/August2022/SmartSecurity/templates/IAmap.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    SmartSecurity
{% endblock title %}

{% block body %}
    <span><h1>Sm</h1><h6>a</h6><h1>rtSecur</h1><h6>i</h6><h1>ty</h1></span>
    <main>
        {% include 'nav.html' %}
        
        <section class="map">
            {% include 'map.html' %}
        </section>
    </main>
    <nav><nav>
{% endblock body %}

Guadalajara/August2022/SmartSecurity/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock title %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'img/gibaly.ico' %}"/>
</head>
<body>
    {% block body %}
    
    {% endblock body %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/map.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/structure.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>

</body>
</html>

Guadalajara/August2022/SmartSecurity/templates/example.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    socialis
{% endblock title %}

{% block body %}
    <h1>titulo</h1>
    <main>

    </main>
{% endblock body %}

Guadalajara/August2022/SmartSecurity/templates/landingPage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    SmartSecurity
{% endblock title %}

{% block body %}
<svg width="100%" viewBox="0 0 1920 950" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;">
    <g transform="matrix(-0.601585,0,0,0.601585,4013.98,303.557)">
        <path d="M5631.71,277.134C5651.1,270.248 5625,0 5625,0L3705,0L3703.71,320L3803.95,694.104C3849.93,865.68 4026.55,967.653 4198.12,921.68L5393.4,601.408C5541.65,561.682 5637.94,424.404 5631.71,277.134Z" style="fill:rgb(189,189,189);"/>
    </g>
    <path d="M1920,357.121L1920,0L0,0L-1.289,320L98.951,694.104C144.925,865.68 321.548,967.653 493.124,921.68L1688.39,601.408C1809.29,569.015 1895.62,471.763 1920,357.121Z" style="fill:rgb(205,205,205);"/>
    <g transform="matrix(1,0,0,1,99.1063,26.1431)">
        <text x="570.363px" y="494.237px" style="font-size:94px;">Sm</text>
        <text x="711.363px" y="494.237px" style="font-size:94px;">a</text>
        <text x="763.642px" y="494.237px" style="font-size:94px;">rtSecur</text>
        <text x="1070.62px" y="494.237px" style="font-size:94px;">i</text>
        <text x="1087.5px" y="494.237px" style="font-size:94px;">ty</text>
    </g>
    <a href="{% url 'IArosa:map' 'Noviembre' 2022 %}">
        <g transform="matrix(1.06007,0,0,0.909091,-42.0622,11.6906)">
            <path class="cap{{fx.0}}" d="M1088,628.5C1088,619.393 1081.66,612 1073.85,612L819.15,612C811.34,612 805,619.393 805,628.5L805,661.5C805,670.607 811.34,678 819.15,678L1073.85,678C1081.66,678 1088,670.607 1088,661.5L1088,628.5Z"/>
            <clipPath id="_clip1">
                <path d="M1088,628.5C1088,619.393 1081.66,612 1073.85,612L819.15,612C811.34,612 805,619.393 805,628.5L805,661.5C805,670.607 811.34,678 819.15,678L1073.85,678C1081.66,678 1088,670.607 1088,661.5L1088,628.5Z"/>
            </clipPath>
            <g clip-path="url(#_clip1)">
                <g transform="matrix(0.943333,0,0,1.1,45.878,-53.7388)">
                    <text x="921.43px" y="643.666px" style="font-size:24px;fill:white;">Iniciar</text>
                </g>
            </g>
        </g>
    </a>
</svg>

{% endblock body %}

Guadalajara/August2022/SmartSecurity/templates/nav.html
<div class="flaying">
    <nav>
        <ul>
            <li>
                <h4>{{ view.kwargs.month }}</h4>
            </li>
            <li>
                <h4>{{ view.kwargs.year }}</h4>
            </li>
        </ul>
    </nav>

    <section class="navOpc">
        <div>
            {% for i in maps.1 %}
                <a href="{% url 'IArosa:map' i view.kwargs.year %}">
                    <h4>{{ i }}</h4>
                </a>
            {% endfor %}
        </div>
        <div>
            {% for j in maps.2 %}
                <a href="{% url 'IArosa:map' view.kwargs.month j %}">
                    <h4>{{ j }}</h4>
                </a>
            {% endfor %}
        </div>
    </section>
</div>

Guadalajara/August2022/SmartSecurity/templates/page404.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Gibaly - 404
{% endblock title %}

{% block body %}
    <h1>Errooooooooooooooooooor</h1>

{% endblock body %}